---
path: /simple_get
methodhandlers:
  - method: GET
    handler: GET_REQUEST_HANDLER
  - method: HEAD
    handler: HEAD_REQUEST_HANDLER
---
path: /method_options
methodhandlers:
  - method: GET
    handler: GET_REQUEST_HANDLER
  - method: HEAD
    handler: HEAD_REQUEST_HANDLER
---
path: /get_with_body
methodhandlers:
  - method: HEAD
    handler: HEAD_REQUEST_HANDLER
---
path: /method_options2
methodhandlers:
  - method: GET
    handler: GET_REQUEST_HANDLER
  - method: HEAD
    handler: HEAD_REQUEST_HANDLER
  - method: PUT
  - method: POST
---
path: /redirect
methodhandlers:
  - method: GET
    handler: REDIRECT_REQUEST_HANDLER
    redirect: http://0.0.0.0:5000/simple_get
---
path: /index.html
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
  - method: HEAD
    handler: HEAD_REQUEST_HANDLER
---
path: /echo_body
methodhandlers:
  - method: POST
    handler: POST_REQUEST_HANDLER
---
path: /style.css
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /dist/bundle.js
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/apple.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/bacon.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/broccoli.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/cherry.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/cupcake.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/cookie.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/donut.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/egg.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/fries.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/ice-cream.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/pepper.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/pizza.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/soda.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/strawberry.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER
---
path: /images/taco.svg
methodhandlers:
  - method: GET
    handler: FILE_REQUEST_HANDLER