# Java Gradle CircleCI 2.0 configuration file
version: 2
jobs:
  build:

    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/com.olgaboiar.mint

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      CC_TEST_REPORTER_ID: 1ebdaad12e42ab517142e9edd95bf092e830a63fe3237e8284a58a68c314e52e

    steps:
      - checkout
      - run:
          name: Test Logging Artifacts
          command: |
            echo "Logs from Server tests go here" > ~/com.olgaboiar.mint/artifact-1;
      - run:
          name: Test Logging Artifacts
          command: |
            echo "Logs from Logger tests go here" > ~/com.olgaboiar.mint/artifact-2;

      - store_artifacts:
          path: ~/com.olgaboiar.mint/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: ~/com.olgaboiar.mint/artifact-2
          destination: artifact-file2

      - store_artifacts:
          path: ~/com.olgaboiar.mint/test-results/coverage
          destination: coverage


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
                     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                     chmod +x ./cc-test-reporter

      # run tests!
      - run: gradle test jacocoTestReport -i


      - run:
          name: Upload coverage to code climate
          command: |
            export JACOCO_SOURCE_PATH=src/main/java
            ./cc-test-reporter format-coverage ~/com.olgaboiar.mint/test-results/coverage --input-type jacoco --debug
            ./cc-test-reporter upload-coverage
